### ISSUE TITLE
Erro access

### ISSUE THREAD

**Issue by foralcala** [YouTransfer/YouTransfer#160]
I try to start youtransfer but it gives me the following error:

util.js:961
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:961:11)
    at Object.<anonymous> (/home/----/transfers.------.--/node_modules/spdy/lib/spdy/connection.js:86:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/-----/transfers.-----.com/node_modules/spdy/lib/spdy.js:20:19)

npm ERR! Linux 3.10.0-427.10.1.lve1.4.7.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtransfer@1.0.6 start script 'gulp clean && gulp dist && node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the youtransfer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp clean && gulp dist && node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtransfer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls youtransfer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/-----/transfers.---------.com/npm-debug.log

**Comment by foralcala** [comment]
I have reinstalled youtransfer and it gives the following error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'app' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'preapp', 'app', 'postapp' ]
5 info lifecycle youtransfer@1.0.6~preapp: youtransfer@1.0.6
6 silly lifecycle youtransfer@1.0.6~preapp: no script for preapp, continuing
7 info lifecycle youtransfer@1.0.6~app: youtransfer@1.0.6
8 verbose lifecycle youtransfer@1.0.6~app: unsafe-perm in lifecycle true
9 verbose lifecycle youtransfer@1.0.6~app: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/-------/transfers.--------.es/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin
10 verbose lifecycle youtransfer@1.0.6~app: CWD: /home/-----/transfers.-----.es
11 silly lifecycle youtransfer@1.0.6~app: Args: [ '-c', 'node app.js' ]
12 silly lifecycle youtransfer@1.0.6~app: Returned: code: 1  signal: null
13 info lifecycle youtransfer@1.0.6~app: Failed to exec app script
14 verbose stack Error: youtransfer@1.0.6 app: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid youtransfer@1.0.6
16 verbose cwd /home/------/transfers.--------.es
17 error Linux 3.10.0-427.10.1.lve1.4.7.el7.x86_64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "app"
19 error node v7.2.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error youtransfer@1.0.6 app: `node app.js`
22 error Exit status 1
23 error Failed at the youtransfer@1.0.6 app script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the youtransfer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs youtransfer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls youtransfer
23 error There is likely additiona
