### ISSUE TITLE
Failed at the youtransfer@1.1.0 start script 'gulp clean && gulp dist && node app.js'.

### ISSUE THREAD

**Issue by rdnsx** [YouTransfer/YouTransfer#191]
After installing and starting YouTransfer with Node.js under Ubuntu Server 18.04.1 LTS, it start´s and crashes directly with the following:

rockdasnetz@transfer:~/transfer/YouTransfer-master$ sudo PORT=80 npm start

 youtransfer@1.1.0 start /home/rockdasnetz/transfer/YouTransfer-master
 gulp clean && gulp dist && node app.js

[07:30:03] Using gulpfile ~/transfer/YouTransfer-master/gulpfile.js
[07:30:03] Starting 'cleanTask'...
[07:30:03] Finished 'cleanTask' after 140 ms
[07:30:03] Starting 'clean'...
[07:30:03] Finished 'clean' after 117 μs
[07:30:10] Using gulpfile ~/transfer/YouTransfer-master/gulpfile.js
[07:30:10] Starting 'browserifyAppTask'...
[07:30:10] Starting 'browserifyVendorTask'...
[07:30:10] Starting 'copyStaticTask'...
[07:30:10] Starting 'lessTask'...
[07:30:20] Finished 'lessTask' after 10 s
[07:30:44] Finished 'browserifyVendorTask' after 33 s
[07:30:45] Finished 'browserifyAppTask' after 35 s
[07:30:45] Finished 'copyStaticTask' after 35 s
[07:30:45] Starting 'build'...
[07:30:45] Finished 'build' after 141 μs
[07:30:45] Starting 'dist'...
[07:30:45] Finished 'dist' after 334 μs
restify listening at http://[::]:80
07:30:49.771Z  INFO youtransfer: Scheduled cleanup of expired files
/home/rockdasnetz/transfer/YouTransfer-master/lib/localstorage.js:256
                if(files.length <= 0) {
                         ^

TypeError: Cannot read property 'length' of undefined
    at /home/rockdasnetz/transfer/YouTransfer-master/lib/localstorage.js:256:12
    at FSReqWrap.oncomplete (fs.js:135:15)

npm ERR! Linux 4.15.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! youtransfer@1.1.0 start: `gulp clean && gulp dist && node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtransfer@1.1.0 start script 'gulp clean && gulp dist && node app.js'.

**Comment by LouBNielsen** [comment]
1.     Create empty folder
2.	Open git bash in that folder
3.	npm install youtransfer -g
4.	youtransfer init
5.	npm init
6.	npm install
7.	run project with npm start or node app.js
8.	browse 5000

**Comment by sibingangadharan** [comment]
Same error here. any solution?

**Comment by stevesanda** [comment]
I tried this route and experienced the same issue as well.

**Comment by ScottBeeson** [comment]
Same error. Steps above did not help.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle youtransfer@1.0.6~prestart: youtransfer@1.0.6
6 info lifecycle youtransfer@1.0.6~start: youtransfer@1.0.6
7 verbose lifecycle youtransfer@1.0.6~start: unsafe-perm in lifecycle true
8 verbose lifecycle youtransfer@1.0.6~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\inetpub\YouTransfer\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle youtransfer@1.0.6~start: CWD: C:\inetpub\YouTransfer
10 silly lifecycle youtransfer@1.0.6~start: Args: [ '/d /s /c', 'gulp clean && gulp dist && node app.js' ]
11 silly lifecycle youtransfer@1.0.6~start: Returned: code: 1  signal: null
12 info lifecycle youtransfer@1.0.6~start: Failed to exec start script
13 verbose stack Error: youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid youtransfer@1.0.6
15 verbose cwd C:\inetpub\YouTransfer
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
22 error Exit status 1
23 error Failed at the youtransfer@1.0.6 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by ScottBeeson** [comment]
I get this at the `npm install` step

![image](https://user-images.githubusercontent.com/108358/86265209-242c0600-bb89-11ea-8b28-614df9b9418c.png)
