### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by tlachau** [YouTransfer/YouTransfer#201]
I can't seem to get this to start up successfully.  Can someone give me some tips please?  I'm trying to get this running on ubuntu 18.04 LTS.  

`uadmin@youtransfer:~/YouTransferHome$ npm start

> youtransfer@1.0.6 start /home/uadmin/YouTransferHome
> gulp clean && gulp dist && node app.js

[19:25:55] Using gulpfile ~/YouTransferHome/gulpfile.js
[19:25:55] Starting 'cleanTask'...
[19:25:55] Finished 'cleanTask' after 68 ms
[19:25:55] Starting 'clean'...
[19:25:55] Finished 'clean' after 21 μs
[19:25:57] Using gulpfile ~/YouTransferHome/gulpfile.js
[19:25:57] Starting 'browserifyAppTask'...
[19:25:57] Starting 'browserifyVendorTask'...
[19:25:57] Starting 'copyStaticTask'...
[19:25:57] Starting 'lessTask'...
[19:26:00] Finished 'browserifyVendorTask' after 3.37 s
[19:26:01] Finished 'lessTask' after 4.11 s
[19:26:01] Finished 'browserifyAppTask' after 4.39 s
[19:26:01] Finished 'copyStaticTask' after 4.41 s
[19:26:01] Starting 'build'...
[19:26:01] Finished 'build' after 24 μs
[19:26:01] Starting 'dist'...
[19:26:01] Finished 'dist' after 4.32 μs
util.js:302
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:302:11)
    at Object.<anonymous> (/home/uadmin/YouTransferHome/node_modules/spdy/lib/spdy/connection.js:86:6)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/uadmin/YouTransferHome/node_modules/spdy/lib/spdy.js:20:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtransfer@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/uadmin/.npm/_logs/2019-01-31T19_26_02_033Z-debug.log
uadmin@youtransfer:~/YouTransferHome$ cat /home/uadmin/.npm/_logs/2019-01-31T19_26_02_033Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/linuxbrew/.linuxbrew/Cellar/node/11.8.0/bin/node',
1 verbose cli   '/home/linuxbrew/.linuxbrew/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.5.0
3 info using node@v11.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle youtransfer@1.0.6~prestart: youtransfer@1.0.6
6 info lifecycle youtransfer@1.0.6~start: youtransfer@1.0.6
7 verbose lifecycle youtransfer@1.0.6~start: unsafe-perm in lifecycle true
8 verbose lifecycle youtransfer@1.0.6~start: PATH: /home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/uadmin/YouTransferHome/node_modules/.bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle youtransfer@1.0.6~start: CWD: /home/uadmin/YouTransferHome
10 silly lifecycle youtransfer@1.0.6~start: Args: [ '-c', 'gulp clean && gulp dist && node app.js' ]
11 silly lifecycle youtransfer@1.0.6~start: Returned: code: 1  signal: null
12 info lifecycle youtransfer@1.0.6~start: Failed to exec start script
13 verbose stack Error: youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid youtransfer@1.0.6
15 verbose cwd /home/uadmin/YouTransferHome
16 verbose Linux 4.15.0-45-generic
17 verbose argv "/home/linuxbrew/.linuxbrew/Cellar/node/11.8.0/bin/node" "/home/linuxbrew/.linuxbrew/bin/npm" "start"
18 verbose node v11.8.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
22 error Exit status 1
23 error Failed at the youtransfer@1.0.6 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by albertly** [comment]
The same problem

**Comment by stevesanda** [comment]
Same issue.

**Comment by tngoman** [comment]
Same issue
