### ISSUE TITLE
Installation not possible under Debian10 

### ISSUE THREAD

**Issue by alwo-io** [YouTransfer/YouTransfer#208]
See DEBUG Log. This is after npm update; npm rebuild.

----
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'dist' ]
2 info using npm@6.12.0
3 info using node@v10.15.2
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle youtransfer@1.1.0~predist: youtransfer@1.1.0
6 info lifecycle youtransfer@1.1.0~dist: youtransfer@1.1.0
7 verbose lifecycle youtransfer@1.1.0~dist: unsafe-perm in lifecycle true
8 verbose lifecycle youtransfer@1.1.0~dist: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/htdocs/YouTransfer/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle youtransfer@1.1.0~dist: CWD: /var/www/htdocs/YouTransfer
10 silly lifecycle youtransfer@1.1.0~dist: Args: [ '-c', 'gulp clean && gulp dist' ]
11 silly lifecycle youtransfer@1.1.0~dist: Returned: code: 134  signal: null
12 info lifecycle youtransfer@1.1.0~dist: Failed to exec dist script
13 verbose stack Error: youtransfer@1.1.0 dist: `gulp clean && gulp dist`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid youtransfer@1.1.0
15 verbose cwd /var/www/htdocs/YouTransfer
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "dist"
18 verbose node v10.15.2
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 134
22 error youtransfer@1.1.0 dist: `gulp clean && gulp dist`
22 error Exit status 134
23 error Failed at the youtransfer@1.1.0 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

----
Any Ideas?

**Comment by gilgongo** [comment]
I get similar under Ubuntu 18.04 when I run `PORT=8080 npm start` in the application directory:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v14.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle youtransfer@1.0.6~prestart: youtransfer@1.0.6
6 info lifecycle youtransfer@1.0.6~start: youtransfer@1.0.6
7 verbose lifecycle youtransfer@1.0.6~start: unsafe-perm in lifecycle true
8 verbose lifecycle youtransfer@1.0.6~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/youtransfer/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle youtransfer@1.0.6~start: CWD: /opt/youtransfer
10 silly lifecycle youtransfer@1.0.6~start: Args: [ '-c', 'gulp clean && gulp dist && node app.js' ]
11 silly lifecycle youtransfer@1.0.6~start: Returned: code: 1  signal: null
12 info lifecycle youtransfer@1.0.6~start: Failed to exec start script
13 verbose stack Error: youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid youtransfer@1.0.6
15 verbose cwd /opt/youtransfer
16 verbose Linux 5.3.0-51-lowlatency
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.3.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error youtransfer@1.0.6 start: `gulp clean && gulp dist && node app.js`
22 error Exit status 1
23 error Failed at the youtransfer@1.0.6 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
